[theme]
base = "light"
primaryColor = "#4B5EEA"
backgroundColor = "#F5F7FD"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#171B2E"
font = "sans serif"

[server]
maxUploadSize = 500

[browser]
gatherUsageStats = false